name: market_pipeline
version: '1.0.0'
config-version: 2

profile: market_pipeline

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  market_pipeline:
    staging:
      +materialized: view      # staging models are views — no storage cost
      +schema: staging
    intermediate:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table     # mart models are physical tables — fast to query
